# Array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a = a.reshape(1, -1)

In [7]:
a.shape

(1, 3)

In [8]:
a = np.array([1,2,3,4,5,6]) 

In [9]:
a.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a = a.reshape(-1, 2)

In [11]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a[2, 0] = 55

In [13]:
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

- zeros

In [19]:
a = np.zeros([3,3])

In [20]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- ones

In [21]:
a = np.ones([2,3])

In [22]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

- full

In [23]:
a = np.full([3,3], 0)

In [24]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
a = np.full([2,3], 1)

In [26]:
a

array([[1, 1, 1],
       [1, 1, 1]])

- eye

In [27]:
a = np.eye(3)

In [28]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- random.random

In [29]:
a = np.random.random([3,4])

In [30]:
a

array([[0.6227034 , 0.75421217, 0.44140731, 0.15131124],
       [0.1949125 , 0.34758289, 0.51998726, 0.01729808],
       [0.41113414, 0.00892715, 0.41117787, 0.89872379]])

## indexing

In [31]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [32]:
a[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [33]:
a[1, -2]

7

In [35]:
a.shape

(3, 4)

In [40]:
b = a[-1:, 1:3]

In [41]:
b.shape

(1, 2)

In [45]:
b = a[-1, 1:3]

In [46]:
b.shape

(2,)

In [47]:
a[np.arange(3), 1] += 10

In [48]:
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [49]:
np.arange(3)

array([0, 1, 2])

In [50]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [51]:
a[range(3), 1] += 10

In [52]:
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

In [54]:
a[np.arange(3), [1,1,1]] += 10

In [55]:
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [56]:
result_index = a>10

In [57]:
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [58]:
a[result_index]

array([32, 36, 40, 11, 12])

In [59]:
a[a>10]

array([32, 36, 40, 11, 12])

## 元素的数据类型

In [60]:
a = np.array([1,2])

In [61]:
a.dtype

dtype('int64')

In [62]:
a = np.array([1.1,2.2])

In [63]:
a.dtype

dtype('float64')

In [64]:
a = np.array([1,2.2])

In [65]:
a.dtype

dtype('float64')

In [68]:
b = np.array(a, dtype=np.int64)

In [69]:
b

array([1, 2])

# 数学运算

In [70]:
a = np.array([[1,2],
             [3,4]])

In [71]:
b = np.array([[5,6],
             [6,5]])

In [72]:
a + b

array([[6, 8],
       [9, 9]])

In [73]:
np.add(a,b)

array([[6, 8],
       [9, 9]])

In [74]:
a - b

array([[-4, -4],
       [-3, -1]])

In [75]:
np.subtract(a,b)

array([[-4, -4],
       [-3, -1]])

In [76]:
a * b

array([[ 5, 12],
       [18, 20]])

In [77]:
np.multiply(a,b)

array([[ 5, 12],
       [18, 20]])

In [78]:
a / b

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [79]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [80]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [81]:
b = np.array([[1,2,3],
             [4,5,6]])

In [82]:
a.dot(b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [83]:
np.dot(a,b)

array([[ 9, 12, 15],
       [19, 26, 33]])

# 常用函数

- sum

In [84]:
a

array([[1, 2],
       [3, 4]])

In [85]:
np.sum(a)

10

In [86]:
np.sum(a, axis=0)

array([4, 6])

In [87]:
np.sum(a, axis=1)

array([3, 7])

- mean

In [88]:
np.mean(a)

2.5

In [89]:
np.mean(a, axis=0)

array([2., 3.])

In [90]:
np.mean(a, axis=1)

array([1.5, 3.5])

- uniform

In [91]:
np.random.uniform(3,4)

3.298901644372433

- tile

In [93]:
a

array([[1, 2],
       [3, 4]])

In [94]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [95]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

- argsort

In [97]:
a = np.array([[3,6,4,11],
            [5,10,1,3]])

In [98]:
a.argsort()

array([[0, 2, 1, 3],
       [2, 3, 0, 1]])

In [99]:
a.argsort(axis=0)

array([[0, 0, 1, 1],
       [1, 1, 0, 0]])

## 矩阵转置

In [100]:
a

array([[ 3,  6,  4, 11],
       [ 5, 10,  1,  3]])

In [101]:
a.T

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [11,  3]])

In [102]:
np.transpose(a)

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [11,  3]])

# 广播

In [103]:
a = np.array([[1,2,3],
             [2,3,4],
             [12,31,22],
             [2,2,2]])

In [104]:
b = np.array([1,2,3])

In [105]:
for i in range(a.shape[0]):
    a[i, :] += b

In [106]:
a

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [13, 33, 25],
       [ 3,  4,  5]])

In [107]:
a + np.tile(b, (4, 1))

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])

In [108]:
a + b

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])