In [1]:
import numpy as np

In [2]:
X = np.array([[0, 1, 0, 1],
              [1, 0, 1, 1],
              [0, 0, 0, 1],
              [1, 0, 1, 0]])

In [3]:
y = np.array([0,1,0,1])

In [4]:
counts={}
for label in np.unique(y):
    # 对每个类别进行遍历
    # 计算（求和）每个特征中 1 的个数
    counts[label]=X[y==label].sum(axis=0)
print("Feature counts:\n{}".format(counts))

Feature counts:
{0: array([0, 1, 0, 2]), 1: array([2, 0, 2, 1])}


In [5]:
from sklearn.datasets import fetch_20newsgroups

In [6]:
news = fetch_20newsgroups(subset='all')

In [7]:
print(len(news.data), len(news.target_names))

18846 20


In [8]:
print(news.DESCR)

.. _20newsgroups_dataset:

The 20 newsgroups text dataset
------------------------------

The 20 newsgroups dataset comprises around 18000 newsgroups posts on
20 topics split in two subsets: one for training (or development)
and the other one for testing (or for performance evaluation). The split
between the train and test set is based upon a messages posted before
and after a specific date.

This module contains two loaders. The first one,
:func:`sklearn.datasets.fetch_20newsgroups`,
returns a list of the raw texts that can be fed to text feature
extractors such as :class:`sklearn.feature_extraction.text.CountVectorizer`
with custom parameters so as to extract feature vectors.
The second one, :func:`sklearn.datasets.fetch_20newsgroups_vectorized`,
returns ready-to-use features, i.e., it is not necessary to use a feature
extractor.

**Data Set Characteristics:**

    =================   ==========
    Classes                     20
    Samples total            18846
    Dimensionality 

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    news.data, news.target, test_size=0.25, random_state=33
)

In [11]:
print(X_train[0])

From: scotts@math.orst.edu (Scott Settlemier)
Subject: FORSALE: MAG Innovision MX15F 1280x1024
Article-I.D.: gaia.1r7hir$9sk
Distribution: world
Organization: Oregon State University Math Department
Lines: 7
NNTP-Posting-Host: math.orst.edu

MAG Innovision MX15F
Fantastic 15" multiscan monitor that can display up to
1280x1024 noninterlaced (!) with .26 mm dot pitch.
If you are looking for a large crystal clear super vga
monitor then this is for you.
$430   call Scott at (503) 757-3483 or
email scotts@math.orst.edu



In [12]:
print(y_train[0:100])

[ 6  1  5  6  5  3 19  8 19 19  3 16  3  1 13 14  4  8  0 13 13 11 19 16
 10 18  9 19  5  3 15  2  0  8 19 12  9  3 19  0  3  3  8 16 16  6 13  8
  8 11 11 11  6  0 13  3 11  9 15  8  8 14 18  2  3  5 14  8 12 15  0 18
  1  0 13 16 14  7 18  5 15  3  5 17 15  2  8  9 14 10  3 14 11 11  3 15
  6 10 14 19]


In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
vec = CountVectorizer()

In [15]:
X_train = vec.fit_transform(X_train)
X_test = vec.transform(X_test)

In [16]:
X_train.get_shape()

(14134, 150725)

In [17]:
import scipy.sparse as sps

In [18]:
sps.find(X_train[0])[1:]

(array([  4447,   5481,   9352,  11905,  14433,  16311,  17937,  22750,
         27541,  34760,  35136,  35665,  44232,  44384,  47467,  51298,
         54291,  56007,  56181,  57011,  59188,  60066,  63584,  65719,
         65921,  66520,  67665,  74779,  76791,  78632,  79874,  87060,
         88624,  89395,  91899,  93010,  96571,  97204,  98705,  99226,
        101912, 102088, 104942, 105052, 105079, 105230, 109290, 110519,
        122222, 122236, 123300, 127872, 128977, 129553, 132568, 132665,
        132903, 133800, 137926, 138437, 140565, 144286, 144786, 148646],
       dtype=int32),
 array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
        1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 4, 1, 2, 1, 2, 1, 1, 1, 1,
        1, 3, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]))

In [19]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [20]:
mnb = MultinomialNB()

In [21]:
mnb.fit(X_train, y_train)

MultinomialNB()

In [22]:
y_predict = mnb.predict(X_test)

In [23]:
y_test

array([ 8, 15, 13, ...,  1, 19, 11])

In [24]:
print('The Accuracy of Naive Bayes Classifier is:', mnb.score(X_test, y_test))

The Accuracy of Naive Bayes Classifier is: 0.8397707979626485


In [25]:
print(classification_report(y_test, y_predict, target_names=news.target_names))

                          precision    recall  f1-score   support

             alt.atheism       0.86      0.86      0.86       201
           comp.graphics       0.59      0.86      0.70       250
 comp.os.ms-windows.misc       0.89      0.10      0.17       248
comp.sys.ibm.pc.hardware       0.60      0.88      0.72       240
   comp.sys.mac.hardware       0.93      0.78      0.85       242
          comp.windows.x       0.82      0.84      0.83       263
            misc.forsale       0.91      0.70      0.79       257
               rec.autos       0.89      0.89      0.89       238
         rec.motorcycles       0.98      0.92      0.95       276
      rec.sport.baseball       0.98      0.91      0.95       251
        rec.sport.hockey       0.93      0.99      0.96       233
               sci.crypt       0.86      0.98      0.91       238
         sci.electronics       0.85      0.88      0.86       249
                 sci.med       0.92      0.94      0.93       245
         